name: Install NCM ON Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare The Environment
      run: sudo apt update && sudo apt -y install curl unzip coreutils

    - name: Install NCM
      run: source <(curl -LSs sh.ncm.ink)
